### ISSUE TITLE
Add search button and view

### ISSUE THREAD

**Issue by rutgerfarry** [classmere/ios#26]
I'm thinking either a tab at the bottom or button at the top left would be best. Search should run instantly as the user types, but should **cancel the last search query** if not yet returned.

**Comment by rutgerfarry** [comment]
here are the designs:
[home view](https://github.com/classmere/_design/blob/master/ios/home_view%402x.png)
[search view](https://github.com/classmere/_design/blob/master/ios/search_view%402x.png)

**Comment by brandonlee503** [comment]
Completed
