### ISSUE TITLE
Add course and section view

### ISSUE THREAD

**Issue by rutgerfarry** [classmere/ios#28]

**Comment by rutgerfarry** [comment]
Here are the mockups:
## course
![course](https://raw.githubusercontent.com/classmere/_design/master/ios/course_view%402x.png)

## section
![section](https://raw.githubusercontent.com/classmere/_design/master/ios/section_view%402x.png)

**Comment by brandonlee503** [comment]
MVP implementation completed with dd6f8dbd10684677deee3ae651e9a6d93347a77b
