### ISSUE TITLE
Implement Personal Course Lists

### ISSUE THREAD

**Issue by brandonlee503** [classmere/ios#5]
Have users be able to add courses/sections into a personal list for practical purposes.  Most likely will require core data.

**Comment by rutgerfarry** [comment]
This should probably be based on the API, then just cached on the phone until it can be updated. [Haneke](https://github.com/Haneke/HanekeSwift) has a JSON cache we could check out that should be simpler than using CoreData :information_desk_person:

**Comment by brandonlee503** [comment]
Okay so I looked into Haneke a bit, looks like a good implementation to me.  What do you mean when you say based on the API? Like when the user presses the add to list, do you want Haneke to do a network fetch through the API?  And if so, why?  Since we already have all the JSON from filling the tableview with courses, can't we somehow fetch from that instead?

**Comment by rutgerfarry** [comment]
So the source of truth for a someone's courses should be on our server, not someone's device. When someone adds a class to their list, the app should POST that to the classmere api under something like `/users/{username}/courselist`. 

The app can cache the results from getting `/users/{username}/courselist`, but if that's different from what is on-device, the on-device cache should be replaced with the new results (excepting POSTS that might have not been able to send yet from being disconnected)

**Comment by brandonlee503** [comment]
Going to close this for now. MVP's features are currently sufficient.
